version: "3"
services:
  manager:
    image: ghcr.io/legion2/ritam-api:0.5.0-SNAPSHOT
  device1:
    image: ghcr.io/legion2/ritam-api:0.5.0-SNAPSHOT
  device2:
    image: ghcr.io/legion2/ritam-api:0.5.0-SNAPSHOT
  device3:
    image: ghcr.io/legion2/ritam-api:0.5.0-SNAPSHOT
  device4:
    image: ghcr.io/legion2/ritam-api:0.5.0-SNAPSHOT
  device5:
    image: ghcr.io/legion2/ritam-api:0.5.0-SNAPSHOT
