version: "3"
services:
  manager:
    image: ghcr.io/legion2/ritam-api:0.3.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./resources:/resources:ro
  device1:
    image: ghcr.io/legion2/ritam-api:0.3.0
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./resources:/resources:ro
  device2:
    image: ghcr.io/legion2/ritam-api:0.3.0
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - ./resources:/resources:ro
  device3:
    image: ghcr.io/legion2/ritam-api:0.3.0
    restart: unless-stopped
    ports:
      - "8083:8080"
    volumes:
      - ./resources:/resources:ro
  device4:
    image: ghcr.io/legion2/ritam-api:0.3.0
    restart: unless-stopped
    ports:
      - "8084:8080"
    volumes:
      - ./resources:/resources:ro
  device5:
    image: ghcr.io/legion2/ritam-api:0.3.0
    restart: unless-stopped
    ports:
      - "8085:8080"
    volumes:
      - ./resources:/resources:ro
  broker:
    build: ./mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
