version: "3"
services:
  manager:
    image: ghcr.io/legion2/ritam-api:1.0.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./resources:/resources:ro
  device1:
    image: ghcr.io/legion2/ritam-api:1.0.0
    restart: unless-stopped
    command: [ "/resources/device-entrypoint.sh" ]
    ports:
      - "8081:8080"
    volumes:
      - ./resources:/resources:ro
  device2:
    image: ghcr.io/legion2/ritam-api:1.0.0
    restart: unless-stopped
    command: [ "/resources/device-entrypoint.sh" ]
    ports:
      - "8082:8080"
    volumes:
      - ./resources:/resources:ro
  device3:
    image: ghcr.io/legion2/ritam-api:1.0.0
    restart: unless-stopped
    command: [ "/resources/device-entrypoint.sh" ]
    ports:
      - "8083:8080"
    volumes:
      - ./resources:/resources:ro
  device4:
    image: ghcr.io/legion2/ritam-api:1.0.0
    restart: unless-stopped
    command: [ "/resources/device-entrypoint.sh" ]
    ports:
      - "8084:8080"
    volumes:
      - ./resources:/resources:ro
  device5:
    image: ghcr.io/legion2/ritam-api:1.0.0
    restart: unless-stopped
    command: [ "/resources/device-entrypoint.sh" ]
    ports:
      - "8085:8080"
    volumes:
      - ./resources:/resources:ro
  manager-setup:
    build: manager-setup
    volumes:
      - ./resources:/resources:ro
    depends_on:
      manager:
        condition: service_healthy
  broker:
    build: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
